### ISSUE TITLE
Requires restart to enable

### ISSUE THREAD

**Issue by Hunanbean** [jsartelle/obsidian-auto-split#2] opened 2022-01-09 03:54 UTC
Not a major issue, but for some time i thought the plugin was not working because unlike many others, this plugin requires an Obsidian close and re-open to enable.

Thank you for the helpful plugin

**Comment by jsartelle** [comment] 2022-01-10 02:37
That's strange, it should work as soon as you enable it. It does for me on the latest Obsidian (Mac).

Do you get any messages in the developer console when you enable it and try to use it?

**Comment by Hunanbean** [comment] 2022-01-10 04:01
on Manjaro Linux, Obsidian 0.13.19

Here is the output from a fresh vault. Actions taken:
Turned off safe mode.
Installed plugin using Obsidians built in downloader/installer.
Enabled plugin.
Noted plugin not working.
Restarted Obsidian - Plugin working. 

[ConsoleOutput.md](https://github.com/jsartelle/obsidian-auto-split/files/7836736/ConsoleOutput.md)
Thank you

**Comment by Hunanbean** [comment] 2022-01-12 22:52
Clarification: This works without restart when i am just enabling/disabling it. I am referring to a restart required the first time you install it, or uninstall and reinstall it.

You would need to clear the Obsidian cache to see the issue, since you have already had t installed and functioning once.

**Comment by jsartelle** [comment] 2022-01-13 00:43
Thanks for the clarification, I was able to reproduce. I left `styles.css` out of the release since I'm not using it, and Obsidian doesn't seem to like that. I updated the release, so this should be fixed now.

**Closed as completed by jsartelle** 2022-01-13 00:43 UTC
